AE-1409 Update NPM package versions and readme md
arbitraryexecution/compound-monitoring pull request #84
Opened 2022-06-01 16:42 UTC by Nomad-AE

Updated all of the NPM package of all of the bots except for the breaking changes of `forta-agent`

Updates NOT implemented:
asset-monitor forta-agent 0.0.39 to 0.1.6
ctoken-monitor forta-agent 0.0.39 to 0.1.6
governance forta-agent 0.0.39 to 0.1.6
large-borrows-governance forta-agent 0.0.39 to 0.1.6
oracle-price-monitor forta-agent 0.0.39 to 0.1.6

2022-06-01 16:59 UTC, echoAE requested changes
Actually, it appears that the newer versions of ESLint are creating additional warnings that need to be addressed before we merged this in.

2022-06-02 11:04 UTC, Nomad-AE commented on README.md
> +### cToken Underlying Asset Monitor
Fixed in commit 9a15d242b799fe1838981b426579cf89ca281af6

2022-06-02 11:05 UTC, Nomad-AE commented
Added links, linted all js files, and fixed some spelling typos.

2022-06-02 13:18 UTC, echoAE approved these changes

2022-06-03 18:04 UTC, darian-ae approved these changes
Looks good, the biggest suggestion was changing the `eslint-plugin-import` to `"eslint-plugin-import": "^2.26.0",` for consistency on all the bots

2022-06-03 18:04 UTC, darian-ae commented on multisig-transactions-monitor/package.json
>      "eslint-config-airbnb": "^19.0.4",
```suggestion
    "eslint-config-airbnb-base": "^15.0.0",
```

Suggesting this for consistency with all the other bots

2022-06-03 18:04 UTC, darian-ae commented on oracle-price-monitor/package.json
>      "eslint-plugin-import": "^2.25.1",
```suggestion
    "eslint-plugin-import": "^2.26.0",
```

2022-06-04 06:11 UTC, merged